//! Flow-managed ownership markers for generated or Flow-owned docs.

/// Marker for `docs/reference/cli.md` generated by Flow.
pub const CLI_REFERENCE_MARKER: &str = "<!-- Flow-Managed: cli-reference v1 -->";

/// Marker for `docs/SUMMARY.md` generated by Flow.
pub const SUMMARY_MARKER: &str = "<!-- Flow-Managed: docs-summary v1 -->";

/// Marker for Flow-maintained documentation pages.
pub const FLOW_DOC_MARKER: &str = "<!-- Flow-Managed: docs-page v1 -->";

/// Legacy marker for release capability pages owned by Flow.
pub const CAPABILITY_PAGE_MARKER: &str = "<!-- Flow-Managed: capability-page v1 -->";

/// Return true when `text` contains `marker` as a complete trimmed line.
#[must_use]
pub fn has_marker(text: &str, marker: &str) -> bool {
    text.lines().any(|line| line.trim() == marker)
}

/// Return true when a page is owned by Flow's central documentation system.
#[must_use]
pub fn is_flow_documentation_page(text: &str) -> bool {
    has_marker(text, FLOW_DOC_MARKER) || has_marker(text, CAPABILITY_PAGE_MARKER)
}
